apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api-deployment
  labels:
    app: contact-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      containers:
      - name: contact-api
        image: contact-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080